modified /etc/usbmount/mount.d/02_setup_measurement to use $UM_MOUNTPOINT instead of a fixed path.

diff --git a/buildroot-external/overlay/base/etc/usbmount/mount.d/02_setup_measurement b/buildroot-external/overlay/base/etc/usbmount/mount.d/02_setup_measurement
--- a/buildroot-external/overlay/base/etc/usbmount/mount.d/02_setup_measurement
+++ b/buildroot-external/overlay/base/etc/usbmount/mount.d/02_setup_measurement
@@ -1,19 +1,21 @@
 #!/bin/sh
-if [ -d "/media/usb0/measurement" ]; then
-	echo "measurement directory already exists"
-	touch "USBinitialised"
-	# CCU2 compatibility
-	touch "SDinitialised"
-else 
-	echo "measurement directory not exists"
-	mkdir /media/usb0/measurement
-	retVal=$?
-	if [ $retVal -ne 0 ]; then
-		echo "error creating measurement directory"
-	else 
-		echo "measurement directory created successfully"
-		touch "/var/status/USBinitialised"
-		# CCU2 compatibility
-		touch "/var/status/SDinitialised"
-	fi
+mountpoint -q ${UM_MOUNTPOINT}
+if [ $? -eq 0 ]; then
+  if [ -d "${UM_MOUNTPOINT}/measurement" ]; then
+    echo "measurement directory already exists"
+    touch "/var/status/USBinitialised"
+    # CCU2 compatibility
+    touch "/var/status/SDinitialised"
+  else 
+    echo "measurement directory not exists"
+    mkdir ${UM_MOUNTPOINT}/measurement
+    if [ $? -ne 0 ]; then
+      echo "error creating measurement directory"
+    else 
+      echo "measurement directory created successfully"
+      touch "/var/status/USBinitialised"
+      # CCU2 compatibility
+      touch "/var/status/SDinitialised"
+    fi
+  fi
 fi
