replaced all static "sleep X" uses with proper access checks using "head -c0" which should help to deal way better with the dynamic device generation process, especially in case of using HomeAssistantOS as the based OS. This refs https://github.com/home-assistant/operating-system/issues/2133#issuecomment-1250932172

diff --git a/buildroot-external/overlay/RFD/etc/init.d/S60multimacd b/buildroot-external/overlay/RFD/etc/init.d/S60multimacd
--- a/buildroot-external/overlay/RFD/etc/init.d/S60multimacd
+++ b/buildroot-external/overlay/RFD/etc/init.d/S60multimacd
@@ -7,6 +7,7 @@
 LOGLEVEL_RFD=5
 CFG_TEMPLATE_DIR=/etc/config_templates
 PIDFILE=/var/run/multimacd.pid
+STEPS=10
 
 [[ -r /var/hm_mode ]] && . /var/hm_mode
 
@@ -22,12 +23,23 @@ init() {
   if [[ ! -c /dev/eq3loop ]]; then
     # load eq3_char_loop kernel module
     modprobe eq3_char_loop
-    sleep 5 # wait for /dev/eq3loop to settle
+
+    # wait until /dev/eq3loop is ready to use
+    for i in $(seq 1 ${STEPS}); do
+      echo -n "."
+      if head -c0 /dev/eq3loop >/dev/null 2>&1; then
+        break
+      fi
+      sleep 1
+    done
+    if [[ ${i} -eq ${STEPS} ]]; then
+      echo "ERROR: couldn't setup /dev/eq3loop"
+      exit 2
+    fi
   fi
 }
 
 waitStartupComplete() {
-  STEPS=10
   for i in $(seq 1 ${STEPS}); do
     sleep 2
     echo -n "."
@@ -41,8 +53,22 @@ waitStartupComplete() {
         sleep 2
         start-stop-daemon -S -N -15 -q -b -m -p ${PIDFILE} --exec /bin/multimacd -- -f /var/etc/multimacd.conf -l ${LOGLEVEL_RFD}
       else
-        sleep 5 # wait for /dev/mmd_* to settle
-        echo "OK"
+        # wait until /dev/mmd_* devices are accessible
+        for j in $(seq 1 ${STEPS}); do
+          echo -n "."
+          if head -c0 /dev/mmd_bidcos >/dev/null 2>&1 &&
+             head -c0 /dev/mmd_hmip >/dev/null 2>&1; then
+            break
+          fi
+          sleep 1
+        done
+
+        if [[ ${j} -eq ${STEPS} ]]; then
+          echo "ERROR: couldn't setup /dev/mmd_* devices"
+          exit 2
+        else
+          echo "OK"
+        fi
         break
       fi
     fi
