fixed all shell scripts so that the shellcheck CI linter check hopefully won't complain anymore.

diff --git a/buildroot-external/overlay/base/etc/init.d/S21rngd b/buildroot-external/overlay/base/etc/init.d/S21rngd
--- a/buildroot-external/overlay/base/etc/init.d/S21rngd
+++ b/buildroot-external/overlay/base/etc/init.d/S21rngd
@@ -1,4 +1,5 @@
 #!/bin/sh
+# shellcheck shell=dash source=/dev/null
 
 NAME="rngd"
 DAEMON="/usr/sbin/${NAME}"
@@ -11,41 +12,46 @@ PID_FILE="/var/run/${NAME}.pid"
 
 start()
 {
-	printf "Starting ${NAME}: "
-	if ! timeout 5 head -c 1 /dev/hwrng >/dev/null 2>&1; then
-		DAEMON_ARGS="${DAEMON_ARGS} -r /dev/urandom"
-	fi
-	start-stop-daemon -S -q -x "${DAEMON}" -- ${DAEMON_ARGS}
-	[ $? = 0 ] && echo "OK" || echo "FAIL"
+  echo -n "Starting ${NAME}: "
+  if ! timeout 5 head -c 1 /dev/hwrng >/dev/null 2>&1; then
+    DAEMON_ARGS="${DAEMON_ARGS} -r /dev/urandom"
+  fi
+
+  # shellcheck disable=SC2086
+  if start-stop-daemon -S -q -x "${DAEMON}" -- ${DAEMON_ARGS}; then
+    echo "OK"
+  else
+    echo "FAIL"
+  fi
 }
 
 stop()
 {
-	printf "Stopping ${NAME}: "
-	# This daemon does not exit properly with the default TERM signal unless
-	# it's forced to work by something reading /dev/random. Killing it and
-	# removing its PID file is more straightforward.
-	if start-stop-daemon -K -q -s KILL -p "${PID_FILE}" -n "${NAME}"; then
-		rm -f "${PID_FILE}"
-		echo "OK"
-	else
-		echo "FAIL"
-	fi
+  echo -n "Stopping ${NAME}: "
+  # This daemon does not exit properly with the default TERM signal unless
+  # it's forced to work by something reading /dev/random. Killing it and
+  # removing its PID file is more straightforward.
+  if start-stop-daemon -K -q -s KILL -p "${PID_FILE}" -n "${NAME}"; then
+    rm -f "${PID_FILE}"
+    echo "OK"
+  else
+    echo "FAIL"
+  fi
 }
 
 case "$1" in
-	start)
-		start
-		;;
-	stop)
-		stop
-		;;
-	restart|reload)
-		stop
-		start
-		;;
-	*)
-		echo "Usage: $0 {start|stop|restart|reload}" >&2
-		exit 1
-		;;
+  start)
+    start
+    ;;
+  stop)
+    stop
+    ;;
+  restart|reload)
+    stop
+    start
+    ;;
+  *)
+    echo "Usage: $0 {start|stop|restart|reload}" >&2
+    exit 1
+    ;;
 esac
