bluetooth support will just be enabled if /etc/config/enableBluetooth is found.

diff --git a/buildroot-external/overlay/base/etc/init.d/S31bluetooth b/buildroot-external/overlay/base/etc/init.d/S31bluetooth
--- a/buildroot-external/overlay/base/etc/init.d/S31bluetooth
+++ b/buildroot-external/overlay/base/etc/init.d/S31bluetooth
@@ -19,49 +19,54 @@ test -f $DAEMON || exit 0
 case $1 in
   start)
     echo -n "Starting bluetooth: "
-    if [[ -c ${DEVICE} ]]; then
+    if [[ -f /etc/config/enableBluetooth ]]; then
+      if [[ -c ${DEVICE} ]]; then
 
-      [[ -r /var/hm_mode ]] && . /var/hm_mode
+        [[ -r /var/hm_mode ]] && . /var/hm_mode
 
-      if [[ "${HM_HOST}" == "tinkerboard" ]]; then
-        HCIATTACH=/usr/bin/rtk_hciattach
-        HCIATTACH_OPT="-s 115200 ${DEVICE} rtk_h5"
+        if [[ "${HM_HOST}" == "tinkerboard" ]]; then
+          HCIATTACH=/usr/bin/rtk_hciattach
+          HCIATTACH_OPT="-s 115200 ${DEVICE} rtk_h5"
+        else
+          HCIATTACH=/usr/bin/hciattach
+          HCIATTACH_OPT="${DEVICE} bcm43xx 921600 noflow -"
+        fi
+
+        # first call will flash the firmware
+        ${RFKILL} unblock bluetooth
+        ${HCIATTACH} ${HCIATTACH_OPT} 2>/dev/null >/dev/null
+        echo -n "."
+
+        # wait for hciattach
+        sleep 2
+
+        # bring hci0 up
+        ${HCICONFIG} dev 2>/dev/null >/dev/null
+        if [ $? -eq 0 ]; then
+          ${HCICONFIG} hci0 up
+
+          start-stop-daemon --start --background ${SSD_OPTIONS}
+          echo "OK"
+
+          exit 0
+        fi
+
+        echo "WARNING: bluetooth setup failed"
       else
-        HCIATTACH=/usr/bin/hciattach
-        HCIATTACH_OPT="${DEVICE} bcm43xx 921600 noflow -"
+        echo "not required"
       fi
-
-      # first call will flash the firmware
-      ${RFKILL} unblock bluetooth
-      ${HCIATTACH} ${HCIATTACH_OPT} 2>/dev/null >/dev/null
-      echo -n "."
-
-      # wait for hciattach
-      sleep 2
-
-      # bring hci0 up
-      ${HCICONFIG} dev 2>/dev/null >/dev/null
-      if [ $? -eq 0 ]; then
-        ${HCICONFIG} hci0 up
-
-        start-stop-daemon --start --background ${SSD_OPTIONS}
-        echo "OK"
-
-        exit 0
-      fi
-
-      echo "WARNING: bluetooth setup failed"
-      ${RFKILL} block bluetooth
     else
-      echo "not required"
+      echo "disabled"
     fi
+
+    ${RFKILL} block bluetooth 2>/dev/null
   ;;
 
   stop)
     echo -n "Stopping bluetooth: "
     start-stop-daemon --stop ${SSD_OPTIONS}
     pkill ".*hciattach"
-    ${RFKILL} block bluetooth
+    ${RFKILL} block bluetooth 2>/dev/null
     echo "OK"
   ;;
 
