switched to using the much more flexible "chrony" deamon for all NTP operations and retired using the old and partly obsolete "ntpd" daemon alltogether. This should make hopefully improve time synchronization with NTP servers as it could cause some issues here/there.

diff --git a/buildroot-external/overlay/base/etc/init.d/S49chrony b/buildroot-external/overlay/base/etc/init.d/S49chrony
--- a/buildroot-external/overlay/base/etc/init.d/S49chrony
+++ b/buildroot-external/overlay/base/etc/init.d/S49chrony
@@ -1,20 +1,21 @@
 #!/bin/sh
 
-NAME=ntpd
-DAEMON=/usr/sbin/$NAME
+NAME=chrony
+DAEMON=/usr/sbin/chronyd
+CLIENT=/usr/bin/chronyc
 CFG_TEMPLATE_DIR=/etc/config_templates
 
 # Gracefully exit if the package has been removed.
 test -x $DAEMON || exit 0
 
 init() {
-	if [[ ! -e /etc/config/ntpclient ]]; then
-		cp $CFG_TEMPLATE_DIR/ntpclient /etc/config
-	fi
+  if [[ ! -e /etc/config/ntpclient ]]; then
+    cp $CFG_TEMPLATE_DIR/ntpclient /etc/config
+  fi
 
-	if [[ -r /etc/config/ntpclient ]]; then
-		. /etc/config/ntpclient
-	fi
+  if [[ -r /etc/config/ntpclient ]]; then
+    . /etc/config/ntpclient
+  fi
 
   # make sure "ntp.homematic.com" is not used anymore
   if [[ "${NTPSERVERS}" == "ntp.homematic.com" ]]; then
@@ -27,10 +28,10 @@ init() {
     NTPSERVERS=$(route -n | awk '{if ($1 == "0.0.0.0") print $2}')
   fi
 
-  # make sure /var/lib/ntp exists so that the drift file
+  # make sure /var/lib/chrony exists so that the drift file
   # can be saved later on
-  if [[ ! -e /var/lib/ntp ]]; then
-    mkdir -p /var/lib/ntp
+  if [[ ! -e /var/lib/${NAME} ]]; then
+    mkdir -p /var/lib/${NAME}
   fi
 }
 
@@ -54,13 +55,26 @@ case "$1" in
       fi
     fi
 
-    # start ntpd
-    start-stop-daemon -S -q -x $DAEMON -- -g ${NTPSERVERS}
-    [ $? = 0 ] && ( echo "OK"; touch /var/status/hasNTP ) || echo "FAIL"
+    # start daemon
+    start-stop-daemon -S -q -x ${DAEMON}
+    if [[ $? -eq 0 ]]; then
+      # use client to add ntp servers
+      for server in ${NTPSERVERS}; do
+        ${CLIENT} add server ${server} >/dev/null 2>&1
+        [ $? = 0 ] && touch /var/status/hasNTP
+      done
+    fi
+
+    if [[ -e /var/status/hasNTP ]]; then
+      ${CLIENT} burst 2/10 >/dev/null 2>&1
+      echo "OK"
+    else
+      echo "FAIL"
+    fi
     ;;
   stop)
     printf "Stopping $NAME: "
-    start-stop-daemon -K -q -n $NAME
+    start-stop-daemon -K -q -p /var/run/chrony/chronyd.pid
     [ $? = 0 ] && echo "OK" || echo "FAIL"
     rm -f /var/status/hasNTP
     ;;
