improved the SSH init script to check for the start-stop-daemon return codes and also start the daemon in foreground so that a proper error message is returned in case the SSH daemon could not be started. (This refs https://homematic-forum.de/forum/viewtopic.php?p=700553#p700550)

diff --git a/buildroot-external/overlay/base/etc/init.d/S50sshd b/buildroot-external/overlay/base/etc/init.d/S50sshd
--- a/buildroot-external/overlay/base/etc/init.d/S50sshd
+++ b/buildroot-external/overlay/base/etc/init.d/S50sshd
@@ -7,6 +7,11 @@
 # Make sure the ssh-keygen progam exists
 [ -f /usr/bin/ssh-keygen ] || exit 0
 
+DAEMON=/usr/sbin/sshd
+PIDFILE=/var/run/sshd.pid
+
+test -x $DAEMON || exit 0
+
 umask 077
 
 start() {
@@ -40,13 +45,25 @@ start() {
     chown root:root /usr/local/etc/ssh/authorized_keys
   fi
 
-  start-stop-daemon -S -q -b -p /var/run/sshd.pid --exec /usr/sbin/sshd -- -D
-  echo "OK"
+  if start-stop-daemon -S -q -p "${PIDFILE}" --exec "${DAEMON}"; then
+    echo "OK"
+  else
+    echo "FAIL"
+    exit 1
+  fi
 }
 stop() {
   echo -n "Stopping sshd: "
-  start-stop-daemon -K -q -p /var/run/sshd.pid
-  echo "OK"
+  if [[ -f ${PIDFILE} ]]; then
+    if start-stop-daemon -K -q -p "${PIDFILE}"; then
+      echo "OK"
+    else
+      echo "FAIL"
+      exit 1
+    fi
+  else
+    echo "OK"
+  fi
 }
 restart() {
   stop
