slightly reworked /bin/checkInternet to not perform the obsolete nfsroot related checks anymore and to be more verbose on execution. In addition we don't us && checks anymore to ensure a more secure execution scheme. (cf. https://homematic-forum.de/forum/viewtopic.php?f=65&t=86236#p841701)

diff --git a/buildroot-external/overlay/base/bin/checkInternet b/buildroot-external/overlay/base/bin/checkInternet
--- a/buildroot-external/overlay/base/bin/checkInternet
+++ b/buildroot-external/overlay/base/bin/checkInternet
@@ -1,24 +1,37 @@
 #!/bin/sh
-if [ ! -e /etc/config/internetCheckDisabled ]; then
+# shellcheck shell=dash disable=SC3010
+
+if [[ ! -e /etc/config/internetCheckDisabled ]]; then
   if ! /usr/bin/timeout 3 /usr/bin/wget -q --spider http://google.com/ >/dev/null 2>&1; then
     if ! /usr/bin/timeout 3 /bin/ping -q -W 3 -c 1 google.com >/dev/null 2>&1; then
       if ! /usr/bin/timeout 3 /usr/bin/nc -z -w 3 google.com 80 >/dev/null 2>&1; then
-        if grep -q nfsroot /proc/cmdline ; then
-          if ! /usr/bin/timeout 3 /bin/ping -q -W 3 -c 1 8.8.8.8 >/dev/null 2>&1; then
-            if ! /usr/bin/timeout 3 /usr/bin/nc -z -w 3 142.250.185.174 80 >/dev/null 2>&1; then
-              [ -f /var/status/hasInternet ] && rm -f /var/status/hasInternet
-              exit 1
-            fi
-          fi
-        else
-          [ -f /var/status/hasInternet ] && rm -f /var/status/hasInternet
-          exit 1
+        echo "Assuming broken internet connectivity: Could not reach google.com."
+        rm -f /var/status/hasInternet
+        if [[ -e /var/status/hasInternet ]]; then
+          echo "ERROR: could not remove /var/status/hasInternet"
         fi
+        exit 1
+      else
+        echo "Assuming internet connectivity: Could reach port 80 on google.com."
       fi
+    else
+      echo "Assuming internet connectivity: Could ping google.com."
     fi
+  else
+    echo "Assuming internet connectivity: Could reach http://google.com via wget."
   fi
+else
+  echo "InternetCheck disabled"
 fi
 
-[ ! -f /var/status/hasInternet ] && touch /var/status/hasInternet
+# if we reach here we ensure that hasInternet is present
+if [[ ! -e /var/status/hasInternet ]]; then
+  echo "Creating /var/status/hasInternet"
+  touch /var/status/hasInternet
+  if [[ ! -e /var/status/hasInternet ]]; then
+    echo "ERROR: could not create /var/status/hasInternet"
+    exit 1
+  fi
+fi
 
 exit 0
