added noLED patch for raspi-fanshim package and also changed daemon startup script to skip the daemon startup in case a HM-MOD-RPI-PCB is used because the Fan SHIM and HM-MOD-RPI-PCB require the same GPIO.1 for their correct operation and thus are incompatible. This refs #811.

diff --git a/buildroot-external/package/raspi-fanshim/S51raspi-fanshim b/buildroot-external/package/raspi-fanshim/S51raspi-fanshim
--- a/buildroot-external/package/raspi-fanshim/S51raspi-fanshim
+++ b/buildroot-external/package/raspi-fanshim/S51raspi-fanshim
@@ -13,15 +13,23 @@ test -x $DAEMON || exit 0
 
 case $1 in
   start)
-    echo -n "Starting FanShim daemon: "
+    echo -n "Starting Fan SHIM daemon: "
 
-    # now start the daemon
-    start-stop-daemon --start --background --pidfile ${PIDFILE} --make-pidfile --quiet --exec ${DAEMON}
-    [[ $? = 0 ]] && echo "OK" || echo "FAIL"
+    # source all data from /var/hm_mode
+    [[ -r /var/hm_mode ]] && . /var/hm_mode
+
+    if [[ "${HM_HMRF_DEV}" == "HM-MOD-RPI-PCB" ]] ||
+       [[ "${HM_HMIP_DEV}" == "HM-MOD-RPI-PCB" ]]; then
+      echo "ERROR: parallel use of Fan SHIM + HM-MOD-RPI-PCB not possible!"
+    else
+      # now start the daemon
+      start-stop-daemon --start --background --pidfile ${PIDFILE} --make-pidfile --quiet --exec ${DAEMON}
+      [[ $? = 0 ]] && echo "OK" || echo "FAIL"
+    fi
   ;;
 
   stop)
-    echo -n "Stopping FanShim daemon: "
+    echo -n "Stopping Fan SHIM daemon: "
     if [[ -f ${PIDFILE} ]]; then
       start-stop-daemon --stop --quiet --pidfile ${PIDFILE}
       [[ $? = 0 ]] && echo "OK" || echo "FAIL"
