reworked lighttpd startup script to use lighttpd-angel for startup. This allows to send a HUP signal to gracefully restart lighttpd and to even monitor crashes and restart it automatically. Also modified restartlighttpd.tcl to use this new functionality. This fixes #184.

diff --git a/buildroot-external/overlay/WebUI/etc/init.d/S50lighttpd b/buildroot-external/overlay/WebUI/etc/init.d/S50lighttpd
--- a/buildroot-external/overlay/WebUI/etc/init.d/S50lighttpd
+++ b/buildroot-external/overlay/WebUI/etc/init.d/S50lighttpd
@@ -18,17 +18,24 @@ start() {
                                                  -subj "/C=DE/O=HomeMatic/OU=$(cat /var/board_serial)/CN=$(hostname)" 2>/dev/null >/dev/null
         fi
 
-	start-stop-daemon -S -q -p /var/run/lighttpd.pid --exec /usr/sbin/lighttpd -- -f /etc/lighttpd/lighttpd.conf
+	start-stop-daemon -S -q -b -m -p /var/run/lighttpd-angel.pid --exec /usr/sbin/lighttpd-angel -- -f /etc/lighttpd/lighttpd.conf -D
 	[[ $? -eq 0 ]] && echo "OK" || echo "ERROR"
 }
 stop() {
 	echo -n "Stopping lighttpd: "
-	start-stop-daemon -K -q -p /var/run/lighttpd.pid
+	start-stop-daemon -K -q -p /var/run/lighttpd-angel.pid
+	rm -f /var/run/lighttpd-angel.pid
 	[[ ! -f /var/run/lighttpd.pid ]] && echo "OK" || echo "ERROR"
 }
 restart() {
 	stop
 	start
+}
+reload() {
+	echo -n "Reloading lighttpd: "
+	start-stop-daemon -K -s HUP -q -p /var/run/lighttpd-angel.pid
+	sleep 2
+	[[ -f /var/run/lighttpd.pid ]] && echo "OK" || echo "ERROR"
 }
 
 case "$1" in
@@ -38,11 +45,14 @@ case "$1" in
   stop)
 	stop
 	;;
-  restart|reload)
+  restart)
 	restart
 	;;
+  reload)
+	reload
+	;;
   *)
-	echo "Usage: $0 {start|stop|restart}"
+	echo "Usage: $0 {start|stop|restart|reload}"
 	exit 1
 esac
 
